"""test_render_keep.py - branch 11, Step 10's wiring slice, sub-step 4: register I-33 in tools/render_diff.py.

What each arm asserts, on synthetic facts only -- nothing is rendered and no page is read:

  K1  --keep-into-logs without --under-review REFUSES, exit 2, a fixed marker, before anything is rendered
      or written; LT_LOGS_DIR points at an empty temporary folder, which stays empty.
  K2  the note beside the kept pages is GENERATED: keep_note, loaded from the file's own syntax tree and
      called on synthetic facts, names the change under review, the pin, the chain actually run -- both
      chains -- and the variant; the hand-written branch-7 body is gone from the file.
  K3  keep_dir names the document AND the variant: a uk and a us run of one document land in two folders.

RED FIRST: run this file from a clean copy of 59981dd (temp/red_wiring), where every arm fails.

    uv run --with lxml python tests/test_render_keep.py
"""
import ast
import io
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parent.parent
TOOL = ROOT / "tools" / "render_diff.py"
MARKER = "REFUSED: --keep-into-logs needs --under-review"
FAIL, CHECKED = [], 0


def ok(label, cond, detail=""):
    global CHECKED
    CHECKED += 1
    print(f"  {'OK  ' if cond else 'XX  '} {label}" + (f"   ({detail})" if detail and not cond else ""))
    if not cond:
        FAIL.append(label)


def load(names):
    """The named top-level functions of render_diff.py, compiled on their own: the script runs its whole
    comparison at import, so it is never imported."""
    tree = ast.parse(TOOL.read_text(encoding="utf-8"))
    keep = [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name in names]
    ns = {"Path": Path}
    exec(compile(ast.Module(body=keep, type_ignores=[]), str(TOOL), "exec"), ns)
    return {n: ns.get(n) for n in names}


print("=" * 88)
print("SUB-STEP 4 — I-33: render_diff's kept pages, their note and their folder")
print("=" * 88)

print("\nK1  --keep-into-logs without --under-review refuses, and nothing is written")
logs = Path(tempfile.mkdtemp(prefix="render-keep-logs-"))
env = dict(os.environ, LT_LOGS_DIR=str(logs), PYTHONIOENCODING="utf-8", PYTHONDONTWRITEBYTECODE="1")
for extra, what in (([], "absent"), (["--under-review", "  "], "blank")):
    r = subprocess.run([sys.executable, str(TOOL), "--doc", "D00", "--keep-into-logs"] + extra,
                       capture_output=True, text=True, encoding="utf-8", errors="replace", cwd=str(ROOT),
                       env=env, timeout=600)
    blob = (r.stdout or "") + (r.stderr or "")
    ok(f"--under-review {what}: exit 2 with the refusal marker", r.returncode == 2 and MARKER in blob,
       f"rc={r.returncode} {blob[-300:]}")
    ok(f"--under-review {what}: ...before anything rendered", "RENDERED PAGE COMPARISON" not in blob)
ok("the logs folder is still empty", list(logs.iterdir()) == [], str(list(logs.iterdir())))
shutil.rmtree(logs, ignore_errors=True)             # REVIEW FIX 8: holds on the failing path too

print("\nK2  the note is generated from the run's facts plus the --under-review line")
fn = load({"keep_note", "keep_dir", "keep_chain"})
if fn["keep_note"] is None:
    ok("keep_note exists in render_diff.py", False)
else:
    # REVIEW FIX 5 (2026-09-30 (3)): the pages WRITTEN, per arm -- the source here renders one page fewer, so
    # its page 5 was never written and the note must not say it was.
    wrote = {"old": [2, 5], "new": [2, 5], "source": [2]}
    for pp, chain in ((False, "apply -> repack"), (True, "apply -> post_process -> reorder -> repack")):
        for v in ("uk", "us"):
            note = fn["keep_note"]("2026-09-30 12:00:00", "D99", v, "abc1234", pp,
                                   "  sub-step 4 of the wiring slice  ", wrote, [5])
            ok(f"[{v}, post_process={pp}] the note names the change, the pin, the chain and the variant",
               all(x in note for x in ("under review:  sub-step 4 of the wiring slice", "pin (-old):    abc1234",
                                       f"chain run:     {chain}  ", f"variant:       {v}",
                                       "document:      D99", "pages changed: [5]")),
               note[:400])
            ok(f"[{v}, post_process={pp}] ...and the pages ACTUALLY written, per arm  the source's missing page 5 "
               "not claimed", "pages written: old [2, 5]  new [2, 5]  source [2]" in note, note[:600])
    ok("an arm that wrote nothing says NONE",
       "source NONE" in fn["keep_note"]("s", "D99", "uk", "abc1234", False, "x",
                                        {"old": [3], "new": [3], "source": []}, [3]))
    ok("...and says it is generated", "GENERATED by tools/render_diff.py" in note)
src = TOOL.read_text(encoding="utf-8")
ok("the hand-written branch-7 body is gone", "Branch 7 rendered comparison" not in src
   and "THE CHANGE UNDER REVIEW IS THE CONTAINER INVENTORY" not in src)
ok("the READ-ME is written from keep_note", 'write_bytes(keep_note(' in src)

print("\nK3  a uk and a us run land in two folders, each naming the document and the variant")
if fn["keep_dir"] is None:
    ok("keep_dir exists in render_diff.py", False)
else:
    a, b = fn["keep_dir"]("L", "D08 #2", "uk"), fn["keep_dir"]("L", "D08 #2", "us")
    ok("two different folders", a != b, f"{a} {b}")
    ok("each names the document and the variant", a.name == "D08n2-uk" and b.name == "D08n2-us", f"{a.name} {b.name}")
    ok("the folders are made by keep_dir where the pages are written", "dest = keep_dir(LOGS, label, args.variant)" in src)

print()
print("=" * 88)
if FAIL:
    print(f"FAIL — {len(FAIL)} of {CHECKED} checks:")
    for f in FAIL:
        print(f"  ·  {f}")
    print("=" * 88)
    sys.exit(1)
print(f"PASS — {CHECKED} checks.")
print("=" * 88)
